import type { RunStatus } from "./app-types.js"
import type { RunStage } from "./run-progress.js"

export type DesktopCopy = ReturnType<typeof desktopCopy>

export function desktopCopy(language: string | undefined) {
  if (language === "zh") {
    return {
      addFiles: "添加文件",
      acceptance: "验收标准",
      activity: "活动",
      activeCount: (count: number) => `${count} 个启用`,
      ask: "询问",
      attachedCount: (count: number) => `已附加 ${count} 个`,
      attachedImages: "附加图片",
      autoReview: "自动审核",
      binary: "二进制",
      build: "执行",
      callCount: (count: number) => `${count} 次调用`,
      cancel: "取消",
      changedFiles: (count: number) => `${count} 个变更`,
      changes: "变更",
      checks: "检查项",
      clean: "干净",
      clear: "清除",
      clearAll: "全部清除",
      clearPlan: "清除计划",
      clearSkills: "清除技能",
      commands: "命令",
      composerPlaceholder: "让 EasyCode 检查、解释、规划或修改这个仓库。",
      configured: "已配置",
      completed: "已完成",
      cannotOpenFile: (filePath: string, message: string) => `无法打开 ${filePath}：${message}`,
      cannotOpenChanges: (message: string) => `无法打开 Git 变更：${message}`,
      certificateIssueDetail: "本地证书链校验失败，通常和代理或系统证书配置有关。请在全局 EasyCode 环境里配置 EASYCODE_EXTRA_CA_CERTS / NODE_EXTRA_CA_CERTS 或代理变量后重启 Desktop。",
      certificateIssueTitle: "证书校验失败",
      copyOutput: "复制回复",
      defaultSessionTitle: "添加桌面 sidecar 客户端",
      details: "详情",
      duration: "时长",
      effort: "推理强度",
      effortHigh: "高",
      effortLow: "低",
      effortMax: "超高",
      effortMedium: "中",
      environment: "环境",
      gitBranch: "Git 分支",
      goal: "目标",
      goalIteration: (status: string, iteration: number) => `${status} · 第 ${iteration} 轮`,
      goalRestricted: "目标受限",
      goalRestrictedTitle: "Goal 模式使用与 CLI 目标自动化一致的受限权限策略。",
      hide: "收起",
      iteration: (iteration: number) => `第 ${iteration} 轮`,
      language: "语言",
      languageName: (code: string) => ({ en: "英文", zh: "中文", ja: "日文", fr: "法文", ko: "韩文", de: "德文" })[code] ?? code,
      localOnly: "仅本地",
      localRepository: "本地仓库",
      maxSteps: "最大步数",
      maxTokens: "最大 Token",
      missing: "缺失",
      model: "模型",
      modified: "已修改",
      newChat: "新对话",
      newSession: "新建会话",
      noActiveGoal: "没有活动目标",
      noActivePlan: "没有活动计划",
      noMessages: "还没有消息。",
      noPathResolved: "未解析到路径",
      noSavedSessions: "没有已保存会话",
      noSkillsFound: "没有找到技能",
      notSelected: "未选择",
      off: "关",
      on: "开",
      openGitChangesInVscode: "在 VS Code 源代码管理中查看",
      openWorkspaceInVscode: "在 VS Code 中打开工作区",
      pause: "暂停",
      permission: "权限",
      plan: "计划",
      planProgress: (completed: number, total: number) => `计划 ${completed}/${total}`,
      promptContext: "上下文",
      provider: "Provider",
      providerDefault: "Provider 默认",
      providerFact: (provider: string) => `provider: ${provider}`,
      providerNotReady: "Provider 未就绪",
      providerStatus: "Provider 状态",
      queue: "排队",
      referencedFiles: "引用文件",
      reasoning: "推理",
      reasoningCount: (count: number) => `${count} 条推理`,
      refresh: "刷新",
      refreshTitle: "重新同步会话、工作区和 sidecar 状态",
      removeWorkspace: "移除工作区",
      resume: "继续",
      run: "运行",
      runFailed: "运行失败",
      runFailedHint: "调整配置后可以直接重试，或继续补充说明。",
      running: "运行中",
      runStatus: (status: RunStatus) => {
        if (status === "waiting_plan") return "等待计划"
        if (status === "waiting_permission") return "等待权限"
        if (status === "idle") return "空闲"
        if (status === "running") return "运行中"
        if (status === "done") return "完成"
        if (status === "failed") return "失败"
        if (status === "blocked") return "受阻"
        return "已取消"
      },
      runState: "运行状态",
      send: "发送",
      show: "展开",
      showAllSkills: (count: number) => `显示全部 ${count} 个技能`,
      showFullResponse: "展开完整回复",
      showInFinder: "在 Finder 中显示",
      showGitChanges: "查看 Git 变更",
      showLess: "收起",
      showSettings: "显示设置",
      sidecar: "Sidecar",
      sidecarPlaceholder: "内置或 PATH 中的 easycode",
      sidecarStatus: "Sidecar 状态",
      skills: "技能",
      startSession: "在这个工作区开始一个本地 EasyCode 会话。",
      starterPrompts: ["检查当前改动", "解释这个项目", "制定一个实现计划", "创建一个目标并持续执行"],
      state: "状态",
      stepProgress: (current: number, total: number) => `步骤 ${current}/${total}`,
      stopped: "已停止",
      runStageLabel: (stage: RunStage) => {
        if (stage === "preparing") return "准备上下文"
        if (stage === "connecting") return "连接模型"
        if (stage === "thinking") return "模型思考中"
        if (stage === "responding") return "正在回复"
        if (stage === "tool") return "执行工具"
        if (stage === "permission") return "等待授权"
        if (stage === "plan") return "等待计划批准"
        return "正在停止"
      },
      thinking: "思考",
      toolCallCount: (count: number) => `${count} 次工具调用`,
      tools: "工具",
      toolsFact: (done: number, total: number) => `工具: ${done}/${total}`,
      modeFact: (mode: string) => `模式: ${mode}`,
      workspace: "工作区",
      workspaceLower: "工作区",
      workingTree: "工作区状态",
      workspaces: "工作区",
      waitingForModel: "正在准备上下文，等待模型响应...",
      you: "你",
    }
  }
  return {
    addFiles: "Add files",
    acceptance: "Acceptance",
    activity: "Activity",
    activeCount: (count: number) => `${count} active`,
    ask: "Ask",
    attachedCount: (count: number) => `${count} attached`,
    attachedImages: "attached images",
    autoReview: "Auto-review",
    binary: "binary",
    build: "Build",
    callCount: (count: number) => `${count} call${count === 1 ? "" : "s"}`,
    cancel: "Cancel",
    changedFiles: (count: number) => `${count} changed`,
    changes: "Changes",
    checks: "Checks",
    clean: "Clean",
    clear: "Clear",
    clearAll: "Clear all",
    clearPlan: "Clear Plan",
    clearSkills: "Clear Skills",
    commands: "Commands",
    composerPlaceholder: "Ask EasyCode to inspect, explain, plan, or change this repository.",
    configured: "Configured",
    completed: "Completed",
    cannotOpenFile: (filePath: string, message: string) => `Cannot open ${filePath}: ${message}`,
    cannotOpenChanges: (message: string) => `Cannot open Git changes: ${message}`,
    certificateIssueDetail: "The local certificate chain could not be verified. This is usually caused by proxy or certificate settings. Configure EASYCODE_EXTRA_CA_CERTS / NODE_EXTRA_CA_CERTS or proxy env vars in the global EasyCode environment, then restart Desktop.",
    certificateIssueTitle: "Certificate verification failed",
    copyOutput: "Copy response",
    defaultSessionTitle: "Add desktop sidecar client",
    details: "details",
    duration: "Duration",
    effort: "Effort",
    effortHigh: "High",
    effortLow: "Low",
    effortMax: "Max",
    effortMedium: "Medium",
    environment: "Environment",
    gitBranch: "Git Branch",
    goal: "Goal",
    goalIteration: (status: string, iteration: number) => `${status} · iter ${iteration}`,
    goalRestricted: "Goal restricted",
    goalRestrictedTitle: "Goal mode uses the same restricted permission policy as the CLI goal automation.",
    hide: "Hide",
    iteration: (iteration: number) => `iteration ${iteration}`,
    language: "Language",
    languageName: (code: string) => ({ en: "English", zh: "Chinese", ja: "Japanese", fr: "French", ko: "Korean", de: "German" })[code] ?? code,
    localOnly: "Local only",
    localRepository: "Local repository",
    maxSteps: "Max Steps",
    maxTokens: "Max Tokens",
    missing: "Missing",
    model: "Model",
    modified: "Modified",
    newChat: "New Chat",
    newSession: "New session",
    noActiveGoal: "No active goal",
    noActivePlan: "No active plan",
    noMessages: "No messages yet.",
    noPathResolved: "No path resolved",
    noSavedSessions: "No saved sessions",
    noSkillsFound: "No skills found",
    notSelected: "Not selected",
    off: "Off",
    on: "On",
    openGitChangesInVscode: "Open Source Control in VS Code",
    openWorkspaceInVscode: "Open workspace in VS Code",
    pause: "Pause",
    permission: "Permission",
    plan: "Plan",
    planProgress: (completed: number, total: number) => `Plan ${completed}/${total}`,
    promptContext: "Prompt Context",
    provider: "Provider",
    providerDefault: "Provider default",
    providerFact: (provider: string) => `provider: ${provider}`,
    providerNotReady: "Provider not ready",
    providerStatus: "Provider Status",
    queue: "Queue",
    referencedFiles: "referenced files",
    reasoning: "Reasoning",
    reasoningCount: (count: number) => `${count} reasoning`,
    refresh: "Refresh",
    refreshTitle: "Sync session, workspace, and sidecar status again",
    removeWorkspace: "Remove Workspace",
    resume: "Resume",
    run: "Run",
    runFailed: "Run failed",
    runFailedHint: "Fix the configuration and retry, or continue with more direction.",
    running: "Running",
    runStatus: displayRunStatus,
    runState: "Run State",
    send: "Send",
    show: "Show",
    showAllSkills: (count: number) => `Show all ${count} skills`,
    showFullResponse: "Show full response",
    showInFinder: "Show in Finder",
    showGitChanges: "View Git changes",
    showLess: "Show less",
    showSettings: "Show settings",
    sidecar: "Sidecar",
    sidecarPlaceholder: "Bundled or PATH easycode",
    sidecarStatus: "Sidecar Status",
    skills: "Skills",
    startSession: "Start a local EasyCode session in this workspace.",
    starterPrompts: ["Review current changes", "Explain this project", "Draft an implementation plan", "Create a goal and keep going"],
    state: "state",
    stepProgress: (current: number, total: number) => `Step ${current}/${total}`,
    stopped: "Stopped",
    runStageLabel: (stage: RunStage) => {
      if (stage === "preparing") return "Preparing context"
      if (stage === "connecting") return "Connecting model"
      if (stage === "thinking") return "Thinking"
      if (stage === "responding") return "Responding"
      if (stage === "tool") return "Running tools"
      if (stage === "permission") return "Waiting for approval"
      if (stage === "plan") return "Waiting for plan"
      return "Stopping"
    },
    thinking: "Thinking",
    toolCallCount: (count: number) => `${count} tool call${count === 1 ? "" : "s"}`,
    tools: "Tools",
    toolsFact: (done: number, total: number) => `tools: ${done}/${total}`,
    modeFact: (mode: string) => `mode: ${mode}`,
    workspace: "Workspace",
    workspaceLower: "workspace",
    workingTree: "Working Tree",
    workspaces: "Workspaces",
    waitingForModel: "Preparing context and waiting for the model...",
    you: "You",
  }
}

function displayRunStatus(status: RunStatus) {
  if (status === "waiting_plan") return "Waiting for plan"
  if (status === "waiting_permission") return "Waiting for permission"
  if (status === "blocked") return "Blocked"
  return status[0].toUpperCase() + status.slice(1)
}
