import { describe, expect, test } from "bun:test"
import path from "node:path"

const repoRoot = path.resolve(import.meta.dir, "../..")

async function rendererFile(relativePath: string) {
  return Bun.file(path.join(repoRoot, "apps/desktop/src/renderer", relativePath)).text()
}

describe("desktop renderer UI contracts", () => {
  test("keeps session creation at the workspace row level only", async () => {
    const source = await rendererFile("App.tsx")
    const css = await rendererFile("styles.css")

    expect(source).toContain('aria-label={`${copy.newSession}: ${workspaceDisplayName(root)}`}')
    expect(source).not.toContain('className="folder-icon"')
    expect(css).not.toContain(".folder-icon")
    expect(css).not.toContain("border-left: 1px solid rgba(148, 163, 184, 0.3)")
    expect(source).not.toContain("session-subtitle")
    expect(source).not.toContain("<span>Sessions</span>")
    expect(source).not.toContain('aria-label="New session"')
  })

  test("remembers the selected desktop session locally", async () => {
    const source = await rendererFile("App.tsx")

    expect(source).toContain("readDesktopSessionSelection")
    expect(source).toContain("resolveStartupWorkspace")
    expect(source).toContain("resolveStartupSession")
    expect(source).toContain("writeDesktopSessionSelection")
    expect(source).toContain("restoreStartupSelection")
    expect(source).toContain("rememberSessionSelection")
  })

  test("opens loaded sessions at the bottom without animated catch-up scrolling", async () => {
    const source = await rendererFile("App.tsx")

    expect(source).toContain("useLayoutEffect")
    expect(source).toContain('const nextStreamScrollRef = useRef<"instant" | "smooth">("smooth")')
    expect(source).toContain('nextStreamScrollRef.current = "smooth"')
    expect(source).toContain("stream.scrollTop = stream.scrollHeight")
    expect(source).toContain('stream.scrollTo({ top: stream.scrollHeight, behavior: "smooth" })')
    expect(source).toContain("function setSessionItems(next: ChatItem[])")
    expect(source).toContain('nextStreamScrollRef.current = "instant"')
    expect(source).toContain("setSessionItems(messagesToItems(loaded.messages))")
  })

  test("opens workspace menus through hover and focus instead of click state", async () => {
    const source = await rendererFile("App.tsx")
    const css = await rendererFile("styles.css")

    expect(source).toContain('className="workspace-menu-host"')
    expect(source).not.toContain("workspaceMenuOpen")
    expect(source).not.toContain("setWorkspaceMenuOpen")
    expect(css).toContain(".workspace-menu {\n  position: absolute")
    expect(css).toContain("display: none")
    expect(css).toContain(".workspace-menu-host::after")
    expect(css).toContain(".workspace-menu-host:hover .workspace-menu")
    expect(css).toContain(".workspace-menu-host:focus-within .workspace-menu")
  })

  test("keeps title, progress, and tool calls in stable desktop regions", async () => {
    const source = await rendererFile("App.tsx")
    const css = await rendererFile("styles.css")

    expect(source).toContain('className="topbar-title"')
    expect(source).toContain("const fullPromptTitle = useMemo(() => firstDisplayUserTitle(items), [items])")
    expect(source).toContain("function fullSessionTitle")
    expect(source).toContain("function firstDisplayUserTitle")
    expect(source).toContain("function isInternalGoalPrompt")
    expect(source).toContain("function internalGoalObjective")
    expect(source).toContain("function safeSessionTitle")
    expect(source).toContain('entries.push({ id: item.id, kind: "message", item: { ...item, text: safeSessionTitle(item.text) } })')
    expect(source).toContain("const displayText = message.role === \"user\" && isInternalGoalPrompt(text) ? safeSessionTitle(text) : text")
    expect(source).toContain("{streamEntries.length === 0 && <EmptyState copy={copy} />}")
    expect(source).not.toContain('className="chips"')
    expect(source).toContain('className="progress-dock"')
    expect(source).toContain("}, [items])")
    expect(source).toContain("const streamEntries = useMemo(() => groupStreamItems(items), [items])")
    expect(source).toContain("function groupAssistantActivity")
    expect(source).toContain("function ActivityGroup")
    expect(source).toContain("parts.flatMap(splitAssistantMessagePart)")
    expect(source).toContain("function splitAssistantMessagePart")
    expect(source).toContain('const text = block.kind === "reasoning" ? `<reasoning>${block.text}</reasoning>` : block.text')
    expect(source).toContain("isAssistantActivityPart(part)")
    expect(source).toContain('return !splitReasoningBlocks(part.item.text).some((block) => block.kind === "markdown")')
    expect(source).toContain("function ToolGroup({ copy, tools }")
    expect(source).toContain("const [open, setOpen] = useState(false)")
    expect(source).toContain('grouped.push({ id: `activity-${first.id}`, kind: "activity", parts: pendingActivity })')
    expect(source).not.toContain("function ToolRow")
    expect(source).toContain("function isPlanControlTool")
    expect(source).toContain('name === "plan_step_complete" || name === "plan_step_fail"')
    expect(source).toContain("function isGoalControlTool")
    expect(source).toContain('name === "goal_set_acceptance" || name === "goal_complete" || name === "goal_blocked"')
    expect(source).toContain("<GoalProgress copy={copy} goal={goal} planStatus={planStatus} />")
    expect(source).toContain("<PlanProgress copy={copy} planStatus={planStatus} />")
    expect(source).toContain("<WorkspaceChangesBar copy={copy} planStatus={planStatus} status={workspaceStatus} onOpen={openWorkspaceChanges} />")
    expect(source).toContain("function planProgressSnapshot")
    expect(source).toContain('className={`plan-inline-dot ${plan.status}`}')
    expect(source).toContain('className="workspace-plan-popover"')
    expect(source).toContain("<GitChangesPanel copy={copy} status={workspaceStatus} />")
    expect(source).toContain('<span className="send-icon" aria-hidden="true" />')
    expect(source).toContain("function assistantOutputText")
    expect(source).toContain("copyToClipboard(outputText)")
    expect(css).toContain("grid-template-rows: auto auto minmax(0, 1fr) auto")
    expect(css).toContain(".topbar-title {\n  display: block")
    expect(css).toContain("padding: 0 14px")
    expect(css).toContain("width: 100%")
    expect(css).toContain("max-width: 100%")
    expect(css).toContain("--desktop-content-width: min(1680px, calc(100% - 32px))")
    expect(css).toContain("justify-items: center")
    expect(css).toContain(".progress-card,\n.empty-state,\n.message,\n.tool-group {\n  width: 100%;\n  max-width: var(--desktop-content-width);\n  margin: 0;\n}")
    expect(css).toContain("text-overflow: ellipsis")
    expect(css).toContain("white-space: nowrap")
    expect(css).toContain(".progress-dock")
    expect(css).toContain(".workspace-changes-bar")
    expect(css).toContain(".plan-inline-dot")
    expect(css).toContain(".workspace-plan-popover")
    expect(css).toContain(".status-plan-step")
    expect(css).toContain(".tool-group")
    expect(css).toContain(".activity-group")
    expect(css).toContain(".activity-toggle")
    expect(css).toContain(".activity-list .message-body {\n  width: 100%;\n  max-width: none;\n  padding: 0;\n}")
    expect(css).toContain(".activity-list .reasoning-fold,\n.activity-list .tool-group")
    expect(css).toContain("background: rgba(247, 249, 253, 0.56)")
    expect(css).toContain("min-height: 30px")
    expect(css).toContain("font-size: 11px")
    expect(css).toContain(".message.assistant-turn .message-body .message-body {\n  width: 100%;\n  padding: 0;\n}")
    expect(css).toContain(".reasoning-fold {\n  width: 100%;")
    expect(css).toContain(".goal-progress")
    expect(css).toContain(".goal-popover")
    expect(css).toContain(".plan-progress")
    expect(css).toContain(".plan-popover")
    expect(css).toContain(".send-icon")
    expect(css).toContain(".copy-output")
    expect(css).toContain("font-size: 28px")
    expect(css).toContain("position: sticky")
    expect(css).not.toContain(".tool-row")
  })

  test("opens workspace changes in the local git changes panel", async () => {
    const main = await Bun.file(path.join(import.meta.dir, "../../apps/desktop/src/main/main.ts")).text()
    const app = await rendererFile("App.tsx")

    expect(app).toContain("function openWorkspaceChanges()")
    expect(app).toContain("setContextRailOpen(true)")
    expect(app).toContain("function GitChangesPanel")
    expect(app).toContain("status?.files ?? []")
    expect(main).toContain('execFileAsync("git", ["diff", "--numstat"]')
    expect(main).toContain("function parseGitNumstat")
  })

  test("uses compact typography for sidebar sessions and message markdown", async () => {
    const css = await rendererFile("styles.css")

    expect(css).toContain(".thread-row")
    expect(css).toContain("min-height: 32px")
    expect(css).toContain("font-size: 13px")
    expect(css).toContain(".markdown-body h1 {\n  font-size: 18px;\n}")
    expect(css).toContain(".markdown-body h2 {\n  font-size: 16px;\n}")
    expect(css).toContain(".markdown-body h3 {\n  font-size: 15px;\n}")
  })

  test("links inline workspace file references to the desktop opener", async () => {
    const source = await rendererFile("App.tsx")
    const css = await rendererFile("styles.css")

    expect(source).toContain("function InlineCode")
    expect(source).toContain("workspaceFileTarget(text)")
    expect(source).toContain("openWorkspaceFileFromMessage")
    expect(source).toContain("copy.cannotOpenFile(filePath, errorMessage(error))")
    expect(source).toContain("props.onOpenFile(target)")
    expect(source).toContain("function pathLooksUnsafe")
    expect(css).toContain(".markdown-body .file-link")
  })

  test("makes settings discoverable and localizes desktop UI copy from language settings", async () => {
    const source = await rendererFile("App.tsx")
    const css = await rendererFile("styles.css")

    expect(source).toContain("const copy = desktopCopy(settings?.language)")
    expect(source).toContain('if (language === "zh")')
    expect(source).toContain('settings: "设置"')
    expect(source).toContain('composerPlaceholder: "让 EasyCode 检查、解释、规划或修改这个仓库。"')
    expect(source).toContain('aria-label={copy.showSettings}')
    expect(source).toContain('className="topbar-settings"')
    expect(source).toContain("languageSelectOptions(copy)")
    expect(source).toContain("copy.languageName(value)")
    expect(source).toContain("isSettingsStatusMessage(text)")
    expect(source).not.toContain('appendStatus(`${result.title}\\n${result.text}`)')
    expect(source).toContain("<Composer")
    expect(source).toContain("copy={copy}")
    expect(css).toContain(".topbar-settings")
  })
})
