import { describe, expect, test } from "bun:test"
import path from "node:path"

const repoRoot = path.resolve(import.meta.dir, "../..")

async function rendererFile(relativePath: string) {
  return Bun.file(path.join(repoRoot, "apps/desktop/src/renderer", relativePath)).text()
}

describe("desktop renderer UI contracts", () => {
  test("keeps stream disclosure keys stable while assistant turns update", async () => {
    const messageStream = await rendererFile("message-stream.tsx")

    expect(messageStream).toContain("pendingAssistantParts.push({ id: `tools-${pendingTools[0].id}`, kind: \"tools\", tools: pendingTools })")
    expect(messageStream).toContain("id: `assistant-turn-${first.id}`")
    expect(messageStream).not.toContain("`tools-${pendingTools[0].id}-${pendingTools[pendingTools.length - 1].id}`")
    expect(messageStream).not.toContain("`assistant-turn-${first.id}-${last.id}`")
  })

  test("keeps session creation at the workspace row level only", async () => {
    const source = await rendererFile("App.tsx")
    const sidebar = await rendererFile("workspace-sidebar.tsx")
    const statusBar = await rendererFile("workspace-status-bar.tsx")
    const css = await rendererFile("styles.css")

    expect(source).toContain('import { WorkspaceSidebar } from "./workspace-sidebar.js"')
    expect(sidebar).toContain('aria-label={`${copy.newSession}: ${workspaceDisplayName(root)}`}')
    expect(source).not.toContain('className="folder-icon"')
    expect(sidebar).not.toContain('className="folder-icon"')
    expect(css).not.toContain(".folder-icon")
    expect(css).not.toContain("border-left: 1px solid rgba(148, 163, 184, 0.3)")
    expect(source).not.toContain("session-subtitle")
    expect(sidebar).not.toContain("session-subtitle")
    expect(sidebar).not.toContain("<span>Sessions</span>")
    expect(sidebar).not.toContain('aria-label="New session"')
  })

  test("remembers the selected desktop session locally", async () => {
    const source = await rendererFile("App.tsx")

    expect(source).toContain("readDesktopSessionSelection")
    expect(source).toContain("resolveStartupWorkspace")
    expect(source).toContain("resolveStartupSession")
    expect(source).toContain("writeDesktopSessionSelection")
    expect(source).toContain("restoreStartupSelection")
    expect(source).toContain("rememberSessionSelection")
  })

  test("opens loaded sessions at the bottom without animated catch-up scrolling", async () => {
    const source = await rendererFile("App.tsx")

    expect(source).toContain("useLayoutEffect")
    expect(source).toContain('const nextStreamScrollRef = useRef<"instant" | "smooth">("smooth")')
    expect(source).toContain('nextStreamScrollRef.current = "smooth"')
    expect(source).toContain("stream.scrollTop = stream.scrollHeight")
    expect(source).toContain('stream.scrollTo({ top: stream.scrollHeight, behavior: "smooth" })')
    expect(source).toContain("function setSessionItems(next: ChatItem[])")
    expect(source).toContain('nextStreamScrollRef.current = "instant"')
    expect(source).toContain("setSessionItems(messagesToItems(loaded.messages))")
  })

  test("opens workspace menus through hover and focus instead of click state", async () => {
    const source = await rendererFile("workspace-sidebar.tsx")
    const css = await rendererFile("styles.css")

    expect(source).toContain('className="workspace-menu-host"')
    expect(source).not.toContain("workspaceMenuOpen")
    expect(source).not.toContain("setWorkspaceMenuOpen")
    expect(css).toContain(".workspace-menu {\n  position: absolute")
    expect(css).toContain("display: none")
    expect(css).toContain(".workspace-menu-host::after")
    expect(css).toContain(".workspace-menu-host:hover .workspace-menu")
    expect(css).toContain(".workspace-menu-host:focus-within .workspace-menu")
  })

  test("keeps title, composer status, and tool calls in stable desktop regions", async () => {
    const source = await rendererFile("App.tsx")
    const sidebar = await rendererFile("workspace-sidebar.tsx")
    const statusBar = await rendererFile("workspace-status-bar.tsx")
    const messageStream = await rendererFile("message-stream.tsx")
    const composer = await rendererFile("composer.tsx")
    const contextRail = await rendererFile("context-rail.tsx")
    const promptModals = await rendererFile("prompt-modals.tsx")
    const desktopCopy = await rendererFile("desktop-copy.ts")
    const css = await rendererFile("styles.css")
    const errorModule = await rendererFile("message-error.ts")
    const progressModule = await rendererFile("run-progress.ts")

    expect(source).toContain('className="topbar-title"')
    expect(source).toContain("<MessageStream")
    expect(source).toContain('import { Composer } from "./composer.js"')
    expect(source).toContain('import { ContextRail } from "./context-rail.js"')
    expect(source).toContain('import { PermissionModal, PlanModal } from "./prompt-modals.js"')
    expect(source).toContain('import { ProviderSetupModal } from "./provider-setup-modal.js"')
    expect(source).toContain("const fullPromptTitle = useMemo(() => firstDisplayUserTitle(items), [items])")
    expect(messageStream).toContain('import { EmptyState } from "./empty-state.js"')
    expect(messageStream).toContain("export function fullSessionTitle")
    expect(messageStream).toContain("export function firstDisplayUserTitle")
    expect(messageStream).toContain("function isInternalGoalPrompt")
    expect(messageStream).toContain("function internalGoalObjective")
    expect(messageStream).toContain("export function safeSessionTitle")
    expect(messageStream).toContain('entries.push({ id: item.id, kind: "message", item: { ...item, text: safeSessionTitle(item.text) } })')
    expect(messageStream).toContain("const displayText = message.role === \"user\" && isInternalGoalPrompt(text) ? safeSessionTitle(text) : text")
    expect(messageStream).toContain("{entries.length === 0 && <EmptyState copy={copy} onSelectPrompt={onSelectPrompt} />}")
    expect(source).not.toContain('className="chips"')
    expect(source).not.toContain('className="progress-dock"')
    expect(source).not.toContain('className="brand-row"')
    expect(source).toContain("}, [items])")
    expect(messageStream).toContain("const entries = groupStreamItems(items)")
    expect(messageStream).toContain("function groupAssistantActivity")
    expect(messageStream).toContain("function ActivityGroup")
    expect(messageStream).toContain("parts.flatMap(splitAssistantMessagePart)")
    expect(messageStream).toContain("function splitAssistantMessagePart")
    expect(messageStream).toContain('const text = block.kind === "reasoning" ? `<reasoning>${block.text}</reasoning>` : block.text')
    expect(messageStream).toContain("isAssistantActivityPart(part)")
    expect(messageStream).toContain('return !splitReasoningBlocks(part.item.text).some((block) => block.kind === "markdown")')
    expect(messageStream).toContain("function ToolGroup({ copy, tools }")
    expect(messageStream).toContain("const [open, setOpen] = useState(false)")
    expect(messageStream).toContain('grouped.push({ id: `activity-${first.id}`, kind: "activity", parts: pendingActivity })')
    expect(messageStream).not.toContain("function ToolRow")
    expect(messageStream).toContain("export function isPlanControlTool")
    expect(messageStream).toContain('name === "plan_step_complete" || name === "plan_step_fail"')
    expect(messageStream).toContain("export function isGoalControlTool")
    expect(messageStream).toContain('name === "goal_set_acceptance" || name === "goal_complete" || name === "goal_blocked"')
    expect(source).not.toContain("function GoalProgress")
    expect(source).not.toContain("function PlanProgress")
    expect(source).toContain('className="composer-stack"')
    expect(source).toContain("<WorkspaceChangesBar copy={copy} goal={goal} planStatus={planStatus} progress={progress} status={workspaceStatus} onOpen={openWorkspaceChanges} />")
    expect(source).toContain("const [sessionsByWorkspace, setSessionsByWorkspace] = useState<Record<string, DesktopSessionSummary[]>>({})")
    expect(source).toContain("const sessions = settings?.workspaceRoot ? sessionsByWorkspace[settings.workspaceRoot] ?? [] : []")
    expect(source).toContain("function setWorkspaceSessions")
    expect(source).toContain("window.easycode.listSessions(workspaceRoot)")
    expect(source).not.toContain("await syncSidecarSession(result.currentSession)")
    expect(source).toContain("<WorkspaceSidebar")
    expect(sidebar).toContain("function SidebarGroup")
    expect(sidebar).toContain("workspace-session-list")
    expect(source).toContain("<Composer")
    expect(composer).toContain("function ComposerDropdown")
    expect(composer).toContain('className="composer-dropdown-trigger"')
    expect(contextRail).toContain('className="panel-dropdown-trigger"')
    expect(promptModals).toContain("sidecarPermissionReply")
    expect(promptModals).toContain("planReplyPayload")
    expect(promptModals).toContain("displayPlanMarkdown")
    expect(promptModals).toContain("<MarkdownText")
    expect(source).not.toContain("function PermissionModal")
    expect(source).not.toContain("function PlanModal")
    expect(source).not.toContain("sidecarPermissionReply")
    expect(source).not.toContain("planReplyPayload")
    expect(source).not.toContain("composer-select-wrap")
    expect(source).toContain('import { WorkspaceChangesBar } from "./workspace-status-bar.js"')
    expect(statusBar).toContain("function planProgressSnapshot")
    expect(statusBar).toContain('className={`plan-inline-dot ${plan.status}`}')
    expect(statusBar).toContain('className="workspace-plan-popover"')
    expect(source).toContain("<ContextRail")
    expect(contextRail).toContain("function GitChangesPanel")
    expect(contextRail).toContain("status?.files ?? []")
    expect(composer).toContain('<span className="send-icon" aria-hidden="true" />')
    expect(messageStream).toContain("function assistantOutputText")
    expect(messageStream).toContain("copyToClipboard(outputText)")
    expect(messageStream).toContain("copy.waitingForModel")
    expect(source).toContain("pending: true")
    expect(messageStream).toContain("function PendingAssistant")
    expect(messageStream).toContain("part.item.pending")
    expect(messageStream).toContain("responseShouldCollapse(outputText, parts)")
    expect(messageStream).toContain("copy.showFullResponse")
    expect(errorModule).toContain("function assistantErrorPresentation")
    expect(errorModule).toContain("unable to get local issuer certificate")
    expect(progressModule).toContain("function runProgressLabel")
    expect(statusBar).toContain("runProgressLabel(progress, copy)")
    expect(source).toContain("stage: \"preparing\"")
    expect(source).toContain("stage: \"responding\"")
    expect(source).toContain("stage: \"tool\"")
    expect(desktopCopy).toContain("starterPrompts")
    expect(messageStream).toContain('className="message-error-card"')
    expect(errorModule).toContain("copy.certificateIssueTitle")
    expect(source).toContain("if (item.pending) return { ...item, text, pending: false }")
    expect(source).toContain("replacePendingAssistant(progressRef.current.summary || `Run ${event.status}.`)")
    expect(source).toContain("function replacePendingAssistant")
    expect(css).toContain("grid-template-rows: auto minmax(0, 1fr) auto")
    expect(css).toContain("grid-template-columns: 280px minmax(0, 1fr)")
    expect(css).toContain(".topbar-title {\n  display: block")
    expect(css).toContain("padding: 0 14px")
    expect(css).toContain("width: 100%")
    expect(css).toContain("max-width: 100%")
    expect(css).toContain("--desktop-content-width: min(1680px, calc(100% - 32px))")
    expect(css).toContain("justify-items: center")
    expect(css).toContain(".empty-state,\n.message,\n.tool-group {\n  width: 100%;\n  max-width: var(--desktop-content-width);\n  margin: 0;\n}")
    expect(css).toContain("text-overflow: ellipsis")
    expect(css).toContain("white-space: nowrap")
    expect(css).not.toContain(".progress-dock")
    expect(css).toContain(".workspace-changes-bar")
    expect(css).toContain(".composer-stack")
    expect(css).toContain(".composer-dropdown-menu")
    expect(css).toContain(".panel-dropdown-menu")
    expect(css).toContain("position: fixed")
    expect(css).toContain("animation: railIn 0.18s ease-out")
    expect(css).toContain(".plan-inline-dot")
    expect(css).toContain(".workspace-plan-popover")
    expect(css).toContain(".status-plan-step")
    expect(css).toContain(".tool-group")
    expect(css).toContain(".activity-group")
    expect(css).toContain(".activity-toggle")
    expect(css).toContain(".activity-list .message-body {\n  width: 100%;\n  max-width: none;\n  padding: 0;\n}")
    expect(css).toContain(".activity-list .reasoning-fold,\n.activity-list .tool-group")
    expect(css).toContain("background: rgba(247, 249, 253, 0.56)")
    expect(css).toContain("min-height: 30px")
    expect(css).toContain("font-size: 11px")
    expect(css).toContain(".message.assistant-turn .message-body .message-body {\n  width: 100%;\n  padding: 0;\n}")
    expect(css).toContain(".pending-assistant")
    expect(css).toContain("@keyframes pendingPulse")
    expect(css).toContain(".message-error-card")
    expect(css).toContain(".message-error-title")
    expect(css).toContain(".starter-prompts")
    expect(css).toContain(".response-compact")
    expect(css).toContain(".response-expand")
    expect(css).toContain(".run-inline-dot")
    expect(css).toContain(".reasoning-fold {\n  width: 100%;")
    expect(css).not.toContain(".goal-progress")
    expect(css).not.toContain(".plan-progress")
    expect(css).toContain(".send-icon")
    expect(css).toContain(".copy-output")
    expect(css).toContain("font-size: 28px")
    expect(css).toContain("position: relative")
    expect(css).not.toContain(".tool-row")
  })

  test("sends composer input on Enter and keeps Shift Enter for new lines", async () => {
    const composer = await rendererFile("composer.tsx")

    expect(composer).toContain('if (event.key !== "Enter" || event.shiftKey || event.nativeEvent.isComposing) return')
    expect(composer).toContain("event.preventDefault()")
    expect(composer).toContain("if (!prompt.trim() || blockedByProvider) return")
    expect(composer).toContain("void sendPrompt()")
    expect(composer).not.toContain("event.metaKey || event.ctrlKey")
  })

  test("opens workspace changes in the local git changes panel", async () => {
    const main = await Bun.file(path.join(import.meta.dir, "../../apps/desktop/src/main/main.ts")).text()
    const app = await rendererFile("App.tsx")
    const contextRail = await rendererFile("context-rail.tsx")

    expect(app).toContain("function openWorkspaceChanges()")
    expect(app).toContain("setContextRailOpen(true)")
    expect(contextRail).toContain("function GitChangesPanel")
    expect(contextRail).toContain("status?.files ?? []")
    expect(main).toContain('execFileAsync("git", ["diff", "--numstat"]')
    expect(main).toContain("function parseGitNumstat")
  })

  test("uses compact typography for sidebar sessions and message markdown", async () => {
    const css = await rendererFile("styles.css")

    expect(css).toContain(".thread-row")
    expect(css).toContain("min-height: 32px")
    expect(css).toContain("font-size: 13px")
    expect(css).toContain(".markdown-body h1 {\n  font-size: 18px;\n}")
    expect(css).toContain(".markdown-body h2 {\n  font-size: 16px;\n}")
    expect(css).toContain(".markdown-body h3 {\n  font-size: 15px;\n}")
  })

  test("links inline workspace file references to the desktop opener", async () => {
    const source = await rendererFile("App.tsx")
    const messageStream = await rendererFile("message-stream.tsx")
    const css = await rendererFile("styles.css")

    expect(messageStream).toContain("function InlineCode")
    expect(messageStream).toContain("workspaceFileTarget(text)")
    expect(source).toContain("openWorkspaceFileFromMessage")
    expect(source).toContain("copy.cannotOpenFile(filePath, errorMessage(error))")
    expect(messageStream).toContain("props.onOpenFile(target)")
    expect(messageStream).toContain("function pathLooksUnsafe")
    expect(css).toContain(".markdown-body .file-link")
  })

  test("makes settings discoverable and localizes desktop UI copy from language settings", async () => {
    const source = await rendererFile("App.tsx")
    const contextRail = await rendererFile("context-rail.tsx")
    const selectOptions = await rendererFile("select-options.ts")
    const messageStream = await rendererFile("message-stream.tsx")
    const desktopCopy = await rendererFile("desktop-copy.ts")
    const css = await rendererFile("styles.css")

    expect(source).toContain("const copy = desktopCopy(settings?.language)")
    expect(source).toContain('import { desktopCopy, type DesktopCopy } from "./desktop-copy.js"')
    expect(source).not.toContain("function desktopCopy")
    expect(desktopCopy).toContain('if (language === "zh")')
    expect(desktopCopy).toContain('showSettings: "显示设置"')
    expect(desktopCopy).toContain('composerPlaceholder: "让 EasyCode 检查、解释、规划或修改这个仓库。"')
    expect(source).toContain('aria-label={copy.showSettings}')
    expect(source).toContain('className="topbar-settings"')
    expect(contextRail).toContain("languageSelectOptions(copy)")
    expect(selectOptions).toContain("copy.languageName(value)")
    expect(messageStream).toContain("isSettingsStatusMessage(text)")
    expect(source).not.toContain('appendStatus(`${result.title}\\n${result.text}`)')
    expect(source).toContain("<Composer")
    expect(source).toContain("copy={copy}")
    expect(css).toContain(".topbar-settings")
  })

  test("turns failed pending runs into visible assistant feedback", async () => {
    const source = await rendererFile("App.tsx")

    expect(source).toContain('} else if (event.type === "failure") {')
    expect(source).toContain("appendAssistant(event.text)")
    expect(source).toContain("replacePendingAssistant(message)")
    expect(source).not.toContain("appendAssistant(error instanceof Error ? error.message : String(error))")
  })

  test("drops stale workspace refresh results after workspace switches", async () => {
    const source = await rendererFile("App.tsx")

    expect(source).toContain("const currentWorkspaceRoot = () => settingsRef.current?.workspaceRoot")
    expect(source).toContain("const isCurrentWorkspace = (workspaceRoot: string | undefined) => settingsRef.current?.workspaceRoot === workspaceRoot")
    expect(source).toContain("const isCurrentSession = (workspaceRoot: string | undefined, session: string | undefined) => isCurrentWorkspace(workspaceRoot) && settingsRef.current?.session === session")
    expect(source).toContain("const readiness = await window.easycode.getProviderReadiness(workspaceRoot)")
    expect(source).toContain("if (!isCurrentWorkspace(workspaceRoot)) return")
    expect(source).toContain("const result = await window.easycode.getGoalStatus(targetSession, workspaceRoot)")
    expect(source).toContain("const result = await window.easycode.getPlanStatus(targetSession, workspaceRoot)")
    expect(source).toContain("if (!isCurrentSession(workspaceRoot, targetSession)) return")
    expect(source).toContain("const status = await window.easycode.workspaceStatus(workspaceRoot)")
  })

  test("binds draft session materialization and sidecar requests to the selected workspace", async () => {
    const source = await rendererFile("App.tsx")
    const main = await Bun.file(path.join(import.meta.dir, "../../apps/desktop/src/main/main.ts")).text()
    const registry = await Bun.file(path.join(import.meta.dir, "../../apps/desktop/src/main/sidecar-registry.ts")).text()

    expect(source).toContain("const workspaceRoot = settingsRef.current?.workspaceRoot")
    expect(source).toContain("const next = await window.easycode.updateSettings({ ...(workspaceRoot ? { workspaceRoot } : {}), session })")
    expect(main).toContain("async function sidecarRequest")
    expect(main).toContain("const activate = requestedRoot === activeRoot")
    expect(main).toContain('registry.configureWorkspace({ ...settings, workspaceRoot: requestedRoot, session: activate ? settings.session : "default" }, { activate })')
    expect(registry).toContain("configureWorkspace(settings: Settings, options: { activate?: boolean } = {})")
    expect(registry).toContain("if (options.activate !== false) this.activeKey = key")
  })
})
