import { describe, expect, test } from "bun:test"
import path from "node:path"

const repoRoot = path.resolve(import.meta.dir, "../..")

describe("desktop renderer UI integration", () => {
  test("renders workspace-owned sessions without a duplicate session toolbar contract", async () => {
    const app = await Bun.file(path.join(repoRoot, "apps/desktop/src/renderer/App.tsx")).text()
    const sidebar = await Bun.file(path.join(repoRoot, "apps/desktop/src/renderer/workspace-sidebar.tsx")).text()
    const statusBar = await Bun.file(path.join(repoRoot, "apps/desktop/src/renderer/workspace-status-bar.tsx")).text()
    const css = await Bun.file(path.join(repoRoot, "apps/desktop/src/renderer/styles.css")).text()

    const workspaceSessionList = sidebar.slice(
      sidebar.indexOf('{active && <div className="workspace-session-list">'),
      sidebar.indexOf("</SidebarGroup>"),
    )

    expect(app).toContain("<WorkspaceSidebar")
    expect(workspaceSessionList).toContain("sessions.map")
    expect(workspaceSessionList).toContain("session-delete")
    expect(workspaceSessionList).not.toContain("session-subtitle")
    expect(workspaceSessionList).not.toContain("New session")
    expect(css).not.toContain(".session-subtitle")
  })

  test("keeps workspace menus hover-driven and tool calls grouped outside scroll-triggering state", async () => {
    const app = await Bun.file(path.join(repoRoot, "apps/desktop/src/renderer/App.tsx")).text()
    const sidebar = await Bun.file(path.join(repoRoot, "apps/desktop/src/renderer/workspace-sidebar.tsx")).text()
    const statusBar = await Bun.file(path.join(repoRoot, "apps/desktop/src/renderer/workspace-status-bar.tsx")).text()
    const messageStream = await Bun.file(path.join(repoRoot, "apps/desktop/src/renderer/message-stream.tsx")).text()
    const composer = await Bun.file(path.join(repoRoot, "apps/desktop/src/renderer/composer.tsx")).text()
    const contextRail = await Bun.file(path.join(repoRoot, "apps/desktop/src/renderer/context-rail.tsx")).text()
    const promptModals = await Bun.file(path.join(repoRoot, "apps/desktop/src/renderer/prompt-modals.tsx")).text()
    const css = await Bun.file(path.join(repoRoot, "apps/desktop/src/renderer/styles.css")).text()

    expect(sidebar).toContain('className="workspace-menu-host"')
    expect(app).not.toContain("workspaceMenuOpen")
    expect(sidebar).not.toContain("workspaceMenuOpen")
    expect(css).toContain(".workspace-menu-host::after")
    expect(css).toContain(".workspace-menu-host:hover .workspace-menu")
    expect(css).toContain(".workspace-menu-host:focus-within .workspace-menu")
    expect(app).toContain("firstDisplayUserTitle(items)")
    expect(messageStream).toContain("isInternalGoalPrompt")
    expect(messageStream).toContain("safeSessionTitle")
    expect(messageStream).toContain('entries.push({ id: item.id, kind: "message", item: { ...item, text: safeSessionTitle(item.text) } })')
    expect(messageStream).toContain("entries.length === 0")
    expect(app).not.toContain('className="progress-dock"')
    expect(app).not.toContain('className="brand-row"')
    expect(messageStream).toContain("groupStreamItems(items)")
    expect(messageStream).toContain('kind: "assistantTurn"')
    expect(messageStream).toContain("function AssistantTurn")
    expect(messageStream).toContain("function ActivityGroup")
    expect(messageStream).toContain("groupAssistantActivity(entry.parts)")
    expect(messageStream).toContain("splitAssistantMessagePart")
    expect(messageStream).toContain("function activitySummary")
    expect(messageStream).toContain("<AssistantTurn copy={copy} key={entry.id} entry={entry} onOpenFile={onOpenFile} />")
    expect(app).toContain("isPlanControlTool(event.toolName)")
    expect(app).toContain("isGoalControlTool(event.toolName)")
    expect(messageStream).toContain("if (isPlanControlTool(item.title) || isGoalControlTool(item.title)) continue")
    expect(app).toContain('className="composer-stack"')
    expect(app).toContain("<WorkspaceChangesBar copy={copy} goal={goal} planStatus={planStatus} progress={progress} status={workspaceStatus} onOpen={openWorkspaceChanges} />")
    expect(app).toContain('import { WorkspaceChangesBar } from "./workspace-status-bar.js"')
    expect(composer).toContain("function ComposerDropdown")
    expect(contextRail).toContain('className="panel-dropdown-trigger"')
    expect(app).toContain('import { PermissionModal, PlanModal } from "./prompt-modals.js"')
    expect(promptModals).toContain("window.easycode.replyPermission")
    expect(promptModals).toContain("window.easycode.replyPlan")
    expect(app).not.toContain("function PermissionModal")
    expect(app).not.toContain("function PlanModal")
    expect(app).not.toContain("function GoalProgress")
    expect(app).not.toContain("function PlanProgress")
    expect(statusBar).toContain("function planProgressSnapshot")
    expect(messageStream).toContain("function ToolGroup({ copy, tools }")
    expect(app).not.toContain("function ToolRow")
    expect(app).not.toContain("setItems: Dispatch<SetStateAction<ChatItem[]>>")
    expect(css).not.toContain(".goal-progress:hover .goal-popover")
    expect(css).not.toContain(".plan-progress:hover .plan-popover")
    expect(css).toContain(".workspace-plan-popover")
    expect(css).toContain(".composer-dropdown-menu")
    expect(css).toContain(".panel-dropdown-menu")
    expect(css).toContain("animation: railIn 0.18s ease-out")
    expect(css).toContain(".activity-group")
    expect(css).toContain(".activity-list")
  })
})
